"""The course-wide energy dataset: loading, provenance, splitting, windowing.

Tutorials 01, 02, 03, 04, 05, 06 and 09 all forecast the *same* series, so the
student can watch a single problem being attacked by seven paradigms. This
module is the single place that decides what that series is and where it came
from.

Two sources are supported:

``synthetic`` (default, shipped in ``data/sample/``)
    Physically motivated simulation from :mod:`ai_power_course.synthetic`.
    Redistributable, deterministic, CI-friendly.

``opsd``
    The real thing: Open Power System Data's ENTSO-E-derived time series for
    Germany. Not committed to the repository — see ``data/README.md`` for the
    licensing reason — but one command away via ``scripts/download_data.py``.

Whatever the source, :func:`load_energy_data` returns the data *together with*
its provenance, and the notebooks print it. Synthetic data must never be
mistaken for measurements.
"""

from __future__ import annotations

import hashlib
import urllib.request
from dataclasses import dataclass
from pathlib import Path
from typing import Literal

import numpy as np
import pandas as pd

from .config import CACHE_DIR, SAMPLE_DIR
from .synthetic import SyntheticConfig, generate_energy_frame

__all__ = [
    "Provenance",
    "CourseDataset",
    "load_energy_data",
    "download_opsd",
    "build_sample_file",
    "TARGET",
    "time_split",
    "add_calendar_features",
    "add_lag_features",
    "make_supervised",
    "make_windows",
    "OPSD_URL",
    "OPSD_CITATION",
]

TARGET = "load_mw"
"""The recurring forecasting target of the course."""

OPSD_VERSION = "2020-10-06"
OPSD_URL = (
    f"https://data.open-power-system-data.org/time_series/{OPSD_VERSION}/"
    "time_series_60min_singleindex.csv"
)
OPSD_CITATION = (
    "Open Power System Data. 2020. Data Package Time series. Version 2020-10-06. "
    "https://doi.org/10.25832/time_series/2020-10-06. "
    "(Primary data from ENTSO-E Transparency.)"
)

#: OPSD column -> course column. Kept explicit so the mapping is auditable.
_OPSD_COLUMNS: dict[str, str] = {
    "DE_load_actual_entsoe_transparency": "load_mw",
    "DE_solar_generation_actual": "pv_mw",
    "DE_wind_generation_actual": "wind_mw",
    "DE_LU_price_day_ahead": "price_eur_mwh",
}

SAMPLE_FILE = SAMPLE_DIR / "energy_synthetic_hourly.csv.gz"


@dataclass(frozen=True)
class Provenance:
    """Where a dataset came from, and what may be claimed about it."""

    source: Literal["synthetic", "opsd"]
    title: str
    is_measurement: bool
    license: str
    citation: str
    notes: str = ""

    def banner(self) -> str:
        """A short block the notebooks print above every experiment."""
        kind = "REAL MEASUREMENTS" if self.is_measurement else "SIMULATED (not measurements)"
        lines = [
            "=" * 78,
            f"DATA PROVENANCE: {kind}",
            f"  source   : {self.source}",
            f"  title    : {self.title}",
            f"  license  : {self.license}",
            f"  cite as  : {self.citation}",
        ]
        if self.notes:
            lines.append(f"  notes    : {self.notes}")
        lines.append("=" * 78)
        return "\n".join(lines)


SYNTHETIC_PROVENANCE = Provenance(
    source="synthetic",
    title="Synthetic European power-system time series (ai_power_course.synthetic)",
    is_measurement=False,
    license="MIT (generated by this repository)",
    citation="Generated by ai_power_course.synthetic.generate_energy_frame, seed 20260101.",
    notes=(
        "Physically motivated simulation. Magnitudes are tuned to resemble Germany "
        "(~479 TWh/a load, PV CF 0.12, wind CF 0.20) but no value is a measurement."
    ),
)

OPSD_PROVENANCE = Provenance(
    source="opsd",
    title="Open Power System Data - Time series (Germany), version 2020-10-06",
    is_measurement=True,
    license="Attribution required; primary data ENTSO-E Transparency. See data/README.md.",
    citation=OPSD_CITATION,
    notes="Downloaded and cached locally; not redistributed with this repository.",
)


@dataclass(frozen=True)
class CourseDataset:
    """An energy time series plus the story of where it came from."""

    frame: pd.DataFrame
    provenance: Provenance

    def __post_init__(self) -> None:
        if not isinstance(self.frame.index, pd.DatetimeIndex):
            raise TypeError("CourseDataset requires a DatetimeIndex")
        if not self.frame.index.is_monotonic_increasing:
            raise ValueError("CourseDataset requires a chronologically sorted index")

    def describe(self) -> str:
        idx = self.frame.index
        return (
            f"{self.provenance.banner()}\n"
            f"rows      : {len(self.frame):,} "
            f"({idx[0]:%Y-%m-%d} to {idx[-1]:%Y-%m-%d}, "
            f"{pd.infer_freq(idx[:100]) or 'irregular'})\n"
            f"columns   : {', '.join(self.frame.columns)}"
        )


# --- loading -----------------------------------------------------------------


def load_energy_data(
    source: Literal["auto", "synthetic", "opsd"] = "auto",
    start: str | None = None,
    end: str | None = None,
) -> CourseDataset:
    """Load the course dataset.

    Parameters
    ----------
    source:
        ``"synthetic"`` always simulates; ``"opsd"`` requires the cached
        download and raises otherwise; ``"auto"`` (the default) uses the OPSD
        cache when a student has downloaded it and falls back to synthetic.
    start, end:
        Optional inclusive/exclusive date bounds, e.g. ``("2018-01-01", None)``.

    Returns
    -------
    CourseDataset
        Never a bare frame: the provenance travels with the numbers.
    """
    if source == "opsd" or (source == "auto" and _opsd_cache_path().exists()):
        dataset = _load_opsd()
    elif source in {"auto", "synthetic"}:
        dataset = _load_synthetic()
    else:  # pragma: no cover - guarded by the Literal
        raise ValueError(f"unknown source {source!r}")

    frame = dataset.frame
    if start is not None:
        frame = frame.loc[frame.index >= pd.Timestamp(start, tz=frame.index.tz)]
    if end is not None:
        frame = frame.loc[frame.index < pd.Timestamp(end, tz=frame.index.tz)]
    return CourseDataset(frame=frame, provenance=dataset.provenance)


def _load_synthetic() -> CourseDataset:
    """Read the committed sample if present, otherwise regenerate it."""
    if SAMPLE_FILE.exists():
        frame = pd.read_csv(SAMPLE_FILE, index_col=0, parse_dates=True)
        frame.index = pd.DatetimeIndex(frame.index).tz_convert("UTC")
        frame.index.name = "time"
    else:
        frame = generate_energy_frame(SyntheticConfig())
    return CourseDataset(frame=frame, provenance=SYNTHETIC_PROVENANCE)


def _opsd_cache_path() -> Path:
    return CACHE_DIR / f"opsd_time_series_60min_{OPSD_VERSION}.csv.gz"


def _load_opsd() -> CourseDataset:
    path = _opsd_cache_path()
    if not path.exists():
        raise FileNotFoundError(
            f"OPSD data not cached at {path}.\n"
            "Run:  uv run python scripts/download_data.py\n"
            "or use load_energy_data(source='synthetic')."
        )
    frame = pd.read_csv(path, index_col=0, parse_dates=True)
    frame.index = pd.DatetimeIndex(frame.index).tz_convert("UTC")
    frame.index.name = "time"
    return CourseDataset(frame=frame, provenance=OPSD_PROVENANCE)


def download_opsd(force: bool = False, chunk_bytes: int = 1 << 20) -> Path:
    """Download the OPSD 60-minute package and cache the German subset.

    The upstream CSV is ~130 MB and 300 columns wide; we keep the four German
    series the course uses plus derived weather-free covariates, which
    compresses to a couple of megabytes. The cache is content-addressed by
    OPSD version, so re-running is a no-op.

    Returns the path to the cached file.
    """
    target = _opsd_cache_path()
    if target.exists() and not force:
        return target

    CACHE_DIR.mkdir(parents=True, exist_ok=True)
    raw = CACHE_DIR / "opsd_raw_60min.csv"
    if not raw.exists() or force:
        tmp = raw.with_suffix(".part")
        with urllib.request.urlopen(OPSD_URL, timeout=300) as response, tmp.open("wb") as handle:
            while chunk := response.read(chunk_bytes):
                handle.write(chunk)
        tmp.replace(raw)

    frame = pd.read_csv(
        raw,
        index_col="utc_timestamp",
        parse_dates=["utc_timestamp"],
        usecols=["utc_timestamp", *_OPSD_COLUMNS],
        low_memory=False,
    )
    frame = frame.rename(columns=_OPSD_COLUMNS)
    frame.index = pd.DatetimeIndex(frame.index).tz_convert("UTC")
    frame.index.name = "time"
    frame = frame.sort_index()
    # Keep the span where every series is populated, then add the derived
    # columns the synthetic frame also carries so notebooks are source-agnostic.
    frame = frame.loc[frame[list(_OPSD_COLUMNS.values())].notna().all(axis=1)]
    frame["residual_load_mw"] = frame["load_mw"] - frame["pv_mw"] - frame["wind_mw"]
    frame["is_weekend"] = frame.index.dayofweek >= 5
    frame.to_csv(target, index=True)
    return target


def build_sample_file(path: Path = SAMPLE_FILE) -> Path:
    """(Re)generate the committed synthetic sample. Used by scripts and tests."""
    path.parent.mkdir(parents=True, exist_ok=True)
    frame = generate_energy_frame(SyntheticConfig())
    frame.to_csv(path, index=True)
    return path


def file_digest(path: Path) -> str:
    """SHA-256 of a file, for the reproducibility checks in ``tests/``."""
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1 << 20), b""):
            digest.update(chunk)
    return digest.hexdigest()


# --- splitting ---------------------------------------------------------------


def time_split(
    frame: pd.DataFrame,
    train_end: str = "2019-01-01",
    valid_end: str = "2020-01-01",
) -> tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame]:
    """Split a time-indexed frame chronologically into train / valid / test.

    Chronological, never random. A random split of a time series lets the model
    interpolate between neighbouring hours it has already seen, which inflates
    every score and is the single most common leak in energy forecasting papers.
    Tutorial 01 demonstrates the damage explicitly.
    """
    tz = frame.index.tz
    train_cut = pd.Timestamp(train_end, tz=tz)
    valid_cut = pd.Timestamp(valid_end, tz=tz)
    if not train_cut < valid_cut:
        raise ValueError("train_end must precede valid_end")
    train = frame.loc[frame.index < train_cut]
    valid = frame.loc[(frame.index >= train_cut) & (frame.index < valid_cut)]
    test = frame.loc[frame.index >= valid_cut]
    if min(len(train), len(valid), len(test)) == 0:
        raise ValueError(
            f"a split is empty (train={len(train)}, valid={len(valid)}, test={len(test)}); "
            "check the cut dates against the data range"
        )
    return train, valid, test


# --- feature engineering -----------------------------------------------------


def add_calendar_features(frame: pd.DataFrame, cyclical: bool = True) -> pd.DataFrame:
    """Append calendar features derived only from the timestamp.

    Calendar features are leak-free by construction: the clock is known for any
    future hour. Cyclical (sine/cosine) encodings stop the model from believing
    that hour 23 and hour 0 are 23 units apart.
    """
    out = frame.copy()
    idx = out.index
    out["hour"] = idx.hour
    out["dayofweek"] = idx.dayofweek
    out["month"] = idx.month
    out["dayofyear"] = idx.dayofyear
    out["is_weekend"] = (idx.dayofweek >= 5).astype(int)
    if cyclical:
        out["hour_sin"] = np.sin(2 * np.pi * idx.hour / 24)
        out["hour_cos"] = np.cos(2 * np.pi * idx.hour / 24)
        out["doy_sin"] = np.sin(2 * np.pi * idx.dayofyear / 365.25)
        out["doy_cos"] = np.cos(2 * np.pi * idx.dayofyear / 365.25)
        out["dow_sin"] = np.sin(2 * np.pi * idx.dayofweek / 7)
        out["dow_cos"] = np.cos(2 * np.pi * idx.dayofweek / 7)
    return out


#: Default lag set: the last few hours, yesterday's same hour, and last week's.
DEFAULT_LAGS: tuple[int, ...] = (0, 1, 2, 3, 23, 24, 25, 48, 167, 168)


def add_lag_features(
    frame: pd.DataFrame,
    column: str = TARGET,
    lags: tuple[int, ...] = DEFAULT_LAGS,
    rolling: tuple[int, ...] = (24, 168),
) -> pd.DataFrame:
    """Append lagged and rolling statistics of ``column``.

    **Convention (important).** Lags are counted from the *forecast origin*
    ``t``, not from the timestamp being predicted: ``{column}_lag{k}`` at row
    ``t`` holds ``column[t - k]``, so ``lag0`` is the most recent observation
    the forecaster actually has. Rolling windows likewise end at ``t``.

    Because every feature is anchored to ``t``, the same feature table is valid
    for *any* forecast horizon — the horizon only shifts the target. Counting
    lags from the predicted timestamp instead is the classic energy-forecasting
    leak: at a 24-hour horizon, "the value one hour before the target" is not
    available when the forecast is made. Tutorial 01 measures what that costs.
    """
    out = frame.copy()
    if min(lags) < 0:
        raise ValueError("lags must be non-negative offsets from the forecast origin")
    for lag in lags:
        out[f"{column}_lag{lag}"] = out[column].shift(lag)
    for window in rolling:
        out[f"{column}_roll{window}_mean"] = out[column].rolling(window).mean()
        out[f"{column}_roll{window}_std"] = out[column].rolling(window).std()
    return out


def make_supervised(
    frame: pd.DataFrame,
    target: str = TARGET,
    horizon: int = 1,
    lags: tuple[int, ...] = DEFAULT_LAGS,
    rolling: tuple[int, ...] = (24, 168),
    exogenous: tuple[str, ...] = (),
    cyclical_calendar: bool = True,
) -> tuple[pd.DataFrame, pd.Series]:
    """Turn a raw time series into the ``(X, y)`` table classical ML expects.

    Row ``t`` is the forecast origin: ``y[t] = target[t + horizon]`` and every
    column of ``X[t]`` is known at ``t`` (see :func:`add_lag_features` for the
    lag convention). Rows with missing lags or a missing target are dropped, so
    ``X`` and ``y`` come back aligned and complete.

    ``exogenous`` columns are taken at time ``t``. For a genuine forecast the
    exogenous values would themselves be a *forecast* (a weather forecast, not
    a weather measurement); tutorial 01 discusses why using the measurement
    flatters the model.
    """
    featured = add_lag_features(frame, column=target, lags=lags, rolling=rolling)
    featured = add_calendar_features(featured, cyclical=cyclical_calendar)

    feature_names = [
        name
        for name in featured.columns
        if name.startswith(f"{target}_lag")
        or name.startswith(f"{target}_roll")
        or name
        in {
            "hour", "dayofweek", "month", "dayofyear", "is_weekend",
            "hour_sin", "hour_cos", "doy_sin", "doy_cos", "dow_sin", "dow_cos",
        }
    ]
    feature_names += [name for name in exogenous if name in featured.columns]

    y = featured[target].shift(-horizon)
    table = featured[feature_names].assign(__y=y).dropna()
    return table.drop(columns="__y"), table["__y"].rename(f"{target}_t+{horizon}")


def make_windows(
    series: np.ndarray | pd.Series,
    context: int = 168,
    horizon: int = 24,
    stride: int = 1,
    covariates: np.ndarray | pd.DataFrame | None = None,
) -> tuple[np.ndarray, np.ndarray]:
    """Slice a series into ``(context, horizon)`` supervised windows.

    Returns ``X`` of shape ``(n_windows, context, n_channels)`` and ``y`` of
    shape ``(n_windows, horizon)``. With no covariates ``n_channels == 1``.
    This is the input format used by the LSTM (tutorial 03) and the Transformer
    (tutorial 06), so both see exactly the same data.
    """
    values = np.asarray(series, dtype=np.float32).reshape(-1)
    if covariates is None:
        channels = values[:, None]
    else:
        extra = np.asarray(covariates, dtype=np.float32)
        if extra.ndim == 1:
            extra = extra[:, None]
        if len(extra) != len(values):
            raise ValueError("covariates must have the same length as the series")
        channels = np.concatenate([values[:, None], extra], axis=1)

    last_start = len(values) - context - horizon
    if last_start < 0:
        raise ValueError(
            f"series of length {len(values)} is too short for context={context}, horizon={horizon}"
        )
    starts = np.arange(0, last_start + 1, stride)
    x = np.stack([channels[s : s + context] for s in starts]).astype(np.float32)
    y = np.stack([values[s + context : s + context + horizon] for s in starts]).astype(np.float32)
    return x, y
