"""Conceptual diagrams, drawn reproducibly with matplotlib.

Every explanatory figure in the course is generated by code in this module
rather than pasted in as an image. Two reasons: the figures stay editable and
version-controllable, and a student who wants to know exactly what a box means
can read the function that drew it.

Each function returns the :class:`~matplotlib.figure.Figure` so a notebook can
adjust or save it.
"""

from __future__ import annotations

import matplotlib.pyplot as plt
import numpy as np
from matplotlib.patches import Circle, FancyArrowPatch, FancyBboxPatch

from .plotting import COLORS

__all__ = [
    "supervised_pipeline",
    "neuron_and_network",
    "backpropagation",
    "rnn_unrolled",
    "lstm_cell",
    "self_supervised_masking",
    "qkv_attention",
    "transformer_block",
    "encoder_decoder_variants",
    "next_token_prediction",
    "pretrain_finetune",
    "lora_diagram",
    "rag_architecture",
    "paradigm_shift",
    "foundation_model_modalities",
    "gridfm_architecture",
    "multi_grid_transfer",
    "ai_timeline",
]

_BOX = {"boxstyle": "round,pad=0.35", "linewidth": 1.3}


def _canvas(width: float = 10.0, height: float = 4.0, xlim=(0, 10), ylim=(0, 4)):
    fig, ax = plt.subplots(figsize=(width, height))
    ax.set_xlim(*xlim)
    ax.set_ylim(*ylim)
    ax.axis("off")
    ax.grid(False)
    return fig, ax


def _box(ax, x, y, w, h, text, color="#ffffff", edge="#333333", fontsize=9, weight="normal"):
    ax.add_patch(
        FancyBboxPatch((x, y), w, h, facecolor=color, edgecolor=edge, **_BOX)
    )
    ax.text(
        x + w / 2, y + h / 2, text, ha="center", va="center",
        fontsize=fontsize, fontweight=weight, wrap=True,
    )


def _arrow(ax, start, end, color="#333333", style="-|>", lw=1.4, ls="-", rad=0.0):
    ax.add_patch(
        FancyArrowPatch(
            start, end, arrowstyle=style, mutation_scale=13, linewidth=lw,
            color=color, linestyle=ls, connectionstyle=f"arc3,rad={rad}",
            shrinkA=2, shrinkB=2,
        )
    )


# --- Stage A: classical ML ---------------------------------------------------


def supervised_pipeline() -> plt.Figure:
    """The classical supervised pipeline of tutorial 01.

    The point of the figure is the *human* in the middle: feature engineering
    is where domain knowledge entered the model, and it is what deep learning
    later automated.
    """
    fig, ax = _canvas(11, 3.0, ylim=(0, 3))
    stages = [
        ("Raw data\n(SCADA, meters,\nweather)", "#f2f2f2"),
        ("Feature\nengineering\n(by a human)", COLORS["accent"]),
        ("Model\n(linear, tree,\nboosting)", COLORS["linear"]),
        ("Prediction\n(load at t+24h)", COLORS["tree"]),
        ("Evaluation\nvs. a baseline", "#f2f2f2"),
    ]
    width, gap = 1.75, 0.45
    for i, (label, color) in enumerate(stages):
        x = 0.3 + i * (width + gap)
        _box(ax, x, 1.0, width, 1.1, label, color=color)
        if i < len(stages) - 1:
            _arrow(ax, (x + width, 1.55), (x + width + gap, 1.55))
    ax.text(
        5.5, 0.45,
        "One dataset  ->  one task  ->  one model.  Change the task and you start again.",
        ha="center", fontsize=9.5, style="italic",
    )
    ax.set_title("Stage A: the classical machine-learning paradigm", fontsize=11, fontweight="bold")
    return fig


def neuron_and_network() -> plt.Figure:
    """A single neuron next to the network it stacks into."""
    fig, axes = plt.subplots(1, 2, figsize=(11, 3.8))
    for ax in axes:
        ax.axis("off")
        ax.grid(False)

    ax = axes[0]
    ax.set_xlim(0, 10)
    ax.set_ylim(0, 6)
    for i, label in enumerate(["x1", "x2", "x3"]):
        y = 4.5 - i * 1.5
        ax.add_patch(Circle((1.2, y), 0.42, facecolor="#f2f2f2", edgecolor="#333"))
        ax.text(1.2, y, label, ha="center", va="center", fontsize=9)
        _arrow(ax, (1.7, y), (4.3, 3.0))
        ax.text(2.9, (y + 3.0) / 2 + 0.22, f"w{i + 1}", fontsize=8.5, color=COLORS["transformer"])
    ax.add_patch(Circle((4.9, 3.0), 0.62, facecolor=COLORS["mlp"], edgecolor="#333"))
    ax.text(4.9, 3.0, r"$\Sigma$", ha="center", va="center", fontsize=13)
    _arrow(ax, (5.55, 3.0), (6.8, 3.0))
    _box(ax, 6.8, 2.35, 1.5, 1.3, "activation\n$\\sigma$", color=COLORS["accent"])
    _arrow(ax, (8.3, 3.0), (9.4, 3.0))
    ax.text(9.6, 3.0, "y", fontsize=10, va="center")
    ax.text(4.9, 1.1, r"$y=\sigma\!\left(\sum_i w_i x_i + b\right)$", ha="center", fontsize=11)
    ax.set_title("One neuron", fontsize=10, fontweight="bold")

    ax = axes[1]
    ax.set_xlim(0, 10)
    ax.set_ylim(0, 6)
    layers = [(1.3, 4, "input"), (4.0, 5, "hidden"), (6.7, 5, "hidden"), (9.0, 1, "output")]
    positions = []
    for x, count, _ in layers:
        ys = np.linspace(1.0, 5.0, count) if count > 1 else [3.0]
        positions.append([(x, y) for y in ys])
    for left, right in zip(positions[:-1], positions[1:], strict=True):
        for x0, y0 in left:
            for x1, y1 in right:
                ax.plot([x0, x1], [y0, y1], color="#cccccc", lw=0.5, zorder=1)
    colours = ["#f2f2f2", COLORS["mlp"], COLORS["mlp"], COLORS["tree"]]
    for (x, _count, name), points, colour in zip(layers, positions, colours, strict=True):
        for px, py in points:
            ax.add_patch(Circle((px, py), 0.28, facecolor=colour, edgecolor="#333", zorder=2))
        ax.text(x, 0.35, name, ha="center", fontsize=8.5)
    ax.set_title("Stacked into a multi-layer perceptron", fontsize=10, fontweight="bold")
    fig.suptitle(
        "Stage B: the model learns its own features", fontsize=11, fontweight="bold", y=1.0
    )
    fig.tight_layout()
    return fig


def backpropagation() -> plt.Figure:
    """Forward pass, loss, and the backward pass that assigns credit."""
    fig, ax = _canvas(11, 3.6)
    nodes = [("x", "#f2f2f2"), ("h = W1 x", COLORS["mlp"]), ("a = relu(h)", COLORS["mlp"]),
             ("y = W2 a", COLORS["tree"]), ("L = (y - t)^2", COLORS["transformer"])]
    width, gap = 1.7, 0.5
    for i, (label, color) in enumerate(nodes):
        x = 0.4 + i * (width + gap)
        _box(ax, x, 2.1, width, 0.95, label, color=color, fontsize=9)
        if i < len(nodes) - 1:
            _arrow(ax, (x + width, 2.58), (x + width + gap, 2.58))
    ax.text(0.4, 3.35, "forward pass: compute the prediction and the loss", fontsize=9.5)

    for i in range(len(nodes) - 1, 0, -1):
        x = 0.4 + i * (width + gap)
        _arrow(
            ax, (x, 1.75), (x - gap, 1.75), color=COLORS["transformer"], ls="--", rad=0.0
        )
    ax.text(
        0.4, 1.1,
        "backward pass: the chain rule propagates dL/d(.) right to left, so every weight "
        "learns\nhow much it contributed to the error. Backpropagation is bookkeeping, not magic.",
        fontsize=9.5, color=COLORS["transformer"],
    )
    ax.set_title("Backpropagation = the chain rule, applied efficiently", fontsize=11,
                 fontweight="bold")
    return fig


def rnn_unrolled() -> plt.Figure:
    """The same cell applied at every time step, with a hidden state carried on."""
    fig, ax = _canvas(11, 3.6)
    steps = 5
    width, gap = 1.35, 0.6
    for t in range(steps):
        x = 0.5 + t * (width + gap)
        _box(ax, x, 1.7, width, 1.0, "RNN\ncell", color=COLORS["rnn"], fontsize=9)
        _arrow(ax, (x + width / 2, 1.0), (x + width / 2, 1.65))
        ax.text(x + width / 2, 0.75, f"$x_{{t-{steps - 1 - t}}}$", ha="center", fontsize=9)
        if t < steps - 1:
            _arrow(ax, (x + width, 2.2), (x + width + gap, 2.2))
            ax.text(x + width + gap / 2, 2.4, "$h$", ha="center", fontsize=8.5)
    x_last = 0.5 + (steps - 1) * (width + gap)
    _arrow(ax, (x_last + width / 2, 2.75), (x_last + width / 2, 3.4))
    ax.text(x_last + width / 2, 3.6, "forecast", ha="center", fontsize=9)
    ax.text(
        0.5, 0.2,
        "The same weights are reused at every step, so the model handles any sequence length —\n"
        "but information must survive the whole chain, and gradients shrink with every hop.",
        fontsize=9.5,
    )
    ax.set_title("A recurrent network, unrolled in time", fontsize=11, fontweight="bold")
    return fig


def lstm_cell() -> plt.Figure:
    """Why gates: an additive cell-state highway past the multiplications."""
    fig, ax = _canvas(10, 4.2)
    _box(ax, 0.6, 0.6, 8.8, 2.9, "", color="#fbfbfb", edge="#999999")
    ax.plot([0.9, 9.1], [3.0, 3.0], color=COLORS["transformer"], lw=2.6)
    ax.text(5.0, 3.25, "cell state $c_t$ — an additive path through time", ha="center",
            fontsize=9.5, color=COLORS["transformer"])
    gates = [
        (1.5, "forget\n$f_t$", "what to drop"),
        (3.6, "input\n$i_t$", "what to write"),
        (5.7, "candidate\n$\\tilde{c}_t$", "what is new"),
        (7.8, "output\n$o_t$", "what to expose"),
    ]
    for x, label, caption in gates:
        _box(ax, x - 0.55, 1.5, 1.2, 0.95, label, color=COLORS["rnn"], fontsize=8.5)
        _arrow(ax, (x + 0.05, 2.5), (x + 0.05, 2.95))
        ax.text(x + 0.05, 1.2, caption, ha="center", fontsize=8)
    ax.text(
        0.6, 0.15,
        "Each gate is a sigmoid in [0,1] multiplying a signal. Because $c_t$ is *added* to rather "
        "than\nrepeatedly multiplied, a gradient can travel hundreds of steps without vanishing.",
        fontsize=9.5,
    )
    ax.set_title("LSTM: gates around an additive memory", fontsize=11, fontweight="bold")
    return fig


# --- Stage C: representations and attention ----------------------------------


def self_supervised_masking() -> plt.Figure:
    """Masked prediction on a load profile — the objective, without labels."""
    rng = np.random.default_rng(7)
    hours = np.arange(24)
    profile = 50 + 9 * np.sin(2 * np.pi * (hours - 4) / 24) + 5 * np.sin(4 * np.pi * hours / 24)
    profile += rng.normal(0, 0.7, 24)
    masked = np.zeros(24, dtype=bool)
    masked[8:12] = True
    masked[18] = True

    fig, axes = plt.subplots(1, 3, figsize=(11.5, 3.0), sharey=True)
    axes[0].plot(hours, profile, color=COLORS["truth"], marker="o", ms=3)
    axes[0].set_title("1. an unlabelled day", fontsize=10)
    visible = profile.copy()
    visible[masked] = np.nan
    axes[1].plot(hours, visible, color=COLORS["truth"], marker="o", ms=3)
    for h in hours[masked]:
        axes[1].axvspan(h - 0.5, h + 0.5, color=COLORS["transformer"], alpha=0.22)
    axes[1].set_title("2. hide part of it", fontsize=10)
    axes[2].plot(hours, visible, color=COLORS["truth"], marker="o", ms=3, label="visible")
    axes[2].plot(hours[masked], profile[masked] + rng.normal(0, 0.8, masked.sum()), "x",
                 color=COLORS["foundation"], ms=8, mew=2, label="reconstructed")
    axes[2].set_title("3. predict it from the rest", fontsize=10)
    axes[2].legend(fontsize=8)
    for ax in axes:
        ax.set_xlabel("hour")
        ax.grid(alpha=0.25)
    axes[0].set_ylabel("load [MW]")
    fig.suptitle(
        "Self-supervised learning: the label is the data itself", fontsize=11, fontweight="bold"
    )
    fig.tight_layout()
    return fig


def qkv_attention() -> plt.Figure:
    """Query, key, value — the lookup metaphor, then the equation."""
    fig, ax = _canvas(11, 4.4, xlim=(0, 11), ylim=(-0.2, 4.4))
    _box(ax, 0.4, 2.9, 2.0, 0.9, "query $q$\n'what am I\nlooking for?'", color=COLORS["mlp"],
         fontsize=8.5)
    _box(ax, 0.4, 1.6, 2.0, 0.9, "keys $K$\n'what does each\nposition offer?'",
         color=COLORS["tree"], fontsize=8.5)
    _box(ax, 0.4, 0.3, 2.0, 0.9, "values $V$\n'what do I return\nif chosen?'",
         color=COLORS["linear"], fontsize=8.5)
    _arrow(ax, (2.5, 3.35), (3.6, 2.6))
    _arrow(ax, (2.5, 2.05), (3.6, 2.4))
    _box(ax, 3.6, 1.9, 2.0, 1.0, "similarity\n$qK^\\top/\\sqrt{d_k}$", color="#f2f2f2",
         fontsize=8.5)
    _arrow(ax, (5.7, 2.4), (6.6, 2.4))
    _box(ax, 6.6, 1.9, 1.6, 1.0, "softmax\n-> weights", color="#f2f2f2", fontsize=8.5)
    _arrow(ax, (8.3, 2.4), (9.2, 2.4))
    _box(ax, 9.2, 1.9, 1.4, 1.0, "output", color=COLORS["foundation"], fontsize=8.5)
    _arrow(ax, (2.5, 0.75), (9.7, 1.85), ls="--", rad=-0.25, color=COLORS["linear"])
    ax.text(
        6.0, 3.9,
        r"$\mathrm{Attention}(Q,K,V)=\mathrm{softmax}\!\left(\frac{QK^\top}{\sqrt{d_k}}\right)V$",
        ha="center", fontsize=13,
    )
    ax.text(
        0.4, -0.12,
        "A soft, differentiable dictionary lookup: instead of retrieving one value, "
        "return a weighted average of all of them.",
        fontsize=9,
    )
    ax.set_title("Scaled dot-product attention", fontsize=11, fontweight="bold")
    return fig


def transformer_block() -> plt.Figure:
    """One pre-norm block, with the two residual streams marked."""
    fig, ax = _canvas(6.2, 6.0, xlim=(0, 6.2), ylim=(0, 6.0))
    ax.plot([0.75, 0.75], [0.5, 5.5], color=COLORS["transformer"], lw=2.2, alpha=0.6)
    ax.text(0.45, 3.0, "residual stream", rotation=90, va="center", fontsize=8.5,
            color=COLORS["transformer"])
    items = [
        (0.8, "LayerNorm", "#f2f2f2"),
        (1.75, "Multi-head\nself-attention", COLORS["mlp"]),
        (2.9, "+  (residual)", "#ffffff"),
        (3.6, "LayerNorm", "#f2f2f2"),
        (4.3, "Feed-forward\n(expand 4x, GELU)", COLORS["tree"]),
        (5.2, "+  (residual)", "#ffffff"),
    ]
    for y, label, colour in items:
        _box(ax, 1.4, y, 3.9, 0.62, label, color=colour, fontsize=8.5)
    _arrow(ax, (3.35, 0.45), (3.35, 0.78))
    ax.text(3.35, 0.2, "input tokens", ha="center", fontsize=8.5)
    _arrow(ax, (3.35, 5.85), (3.35, 5.95))
    ax.text(5.6, 3.0, "stack N of\nthese", fontsize=8.5, rotation=90, va="center")
    ax.set_title("A Transformer block", fontsize=11, fontweight="bold")
    return fig


def encoder_decoder_variants() -> plt.Figure:
    """Encoder / decoder / encoder-decoder, and what each is good for."""
    fig, axes = plt.subplots(1, 3, figsize=(12, 3.6))
    specs = [
        (
            "Encoder-only", COLORS["mlp"], "bidirectional",
            "sees the whole sequence\nat once\n\nBERT, DINOv2,\nChronos-2, GridFM\n\n"
            "-> understanding,\nembeddings, regression",
        ),
        (
            "Decoder-only", COLORS["transformer"], "causal",
            "sees only the past\n(causal mask)\n\nGPT, Llama, Mistral,\nWindFM\n\n"
            "-> generation,\nnext-token prediction",
        ),
        (
            "Encoder-decoder", COLORS["tree"], "both",
            "encode input,\nthen generate output\n\nT5, original\nTransformer, Chronos-1\n\n"
            "-> translation,\nsequence-to-sequence",
        ),
    ]
    for ax, (title, colour, mask, text) in zip(axes, specs, strict=True):
        ax.set_xlim(0, 10)
        ax.set_ylim(0, 10)
        ax.axis("off")
        ax.grid(False)
        _box(ax, 1.0, 7.3, 8.0, 1.6, f"{title}\n({mask} attention)", color=colour, fontsize=9.5,
             weight="bold")
        ax.text(5.0, 4.0, text, ha="center", va="center", fontsize=8.8)
    fig.suptitle(
        "Same block, three ways to mask attention — three different capabilities",
        fontsize=11, fontweight="bold",
    )
    fig.tight_layout()
    return fig


def next_token_prediction() -> plt.Figure:
    """Teacher forcing: every position is a training example."""
    fig, ax = _canvas(11, 3.4)
    tokens = ["The", "bus", "voltage", "exceeded", "1.05", "p.u."]
    width, gap = 1.45, 0.25
    for i, token in enumerate(tokens):
        x = 0.4 + i * (width + gap)
        colour = "#f2f2f2" if i < len(tokens) - 1 else COLORS["accent"]
        _box(ax, x, 1.5, width, 0.75, token, color=colour, fontsize=9)
        if i < len(tokens) - 1:
            _arrow(ax, (x + width / 2, 2.3), (x + width + gap + width / 2, 2.9),
                   color=COLORS["transformer"], rad=0.25)
    ax.text(5.5, 3.3, "each position predicts the next one — simultaneously", ha="center",
            fontsize=9.5, color=COLORS["transformer"])
    ax.text(
        0.4, 0.75,
        "A sequence of length T gives T training signals, not one. That is why next-token\n"
        "prediction scales: the supervision is free and the data is the entire internet.",
        fontsize=9.5,
    )
    ax.set_title("Autoregressive language modelling", fontsize=11, fontweight="bold")
    return fig


# --- Stage D: foundation models ----------------------------------------------


def pretrain_finetune() -> plt.Figure:
    """Pretraining once, adapting many times."""
    fig, ax = _canvas(11, 4.4, ylim=(0, 4.4))
    _box(ax, 0.3, 1.6, 2.6, 1.6,
         "PRETRAINING\nbroad, unlabelled data\nself-supervised objective\nexpensive, done once",
         color=COLORS["foundation"], fontsize=8.5)
    _arrow(ax, (3.0, 2.4), (4.0, 2.4), lw=2.0)
    _box(ax, 4.0, 1.6, 2.2, 1.6, "reusable\nrepresentation\n(the backbone)",
         color=COLORS["accent"], fontsize=9, weight="bold")
    adaptations = [
        (3.5, "zero-shot\n(no training)"),
        (2.3, "few-shot / prompting\n(no weight update)"),
        (1.1, "linear probe / LoRA\n(tiny weight update)"),
        (-0.1, "full fine-tuning\n(all weights)"),
    ]
    for y, label in adaptations:
        _arrow(ax, (6.3, 2.4), (7.4, y + 0.42), rad=0.12)
        _box(ax, 7.4, y, 3.3, 0.85, label, color="#f2f2f2", fontsize=8.5)
    ax.text(0.3, 0.3, "cost: GPU-months, once", fontsize=8.5, color=COLORS["foundation"])
    ax.text(7.4, -0.55, "cost: minutes to hours, per task", fontsize=8.5)
    ax.set_ylim(-0.8, 4.4)
    ax.set_title("Pretraining vs. adaptation", fontsize=11, fontweight="bold")
    return fig


def lora_diagram() -> plt.Figure:
    """Low-rank adaptation: freeze W, learn a thin correction."""
    fig, ax = _canvas(9.5, 4.2, xlim=(0, 9.5), ylim=(0, 4.2))
    _box(ax, 0.4, 1.7, 1.3, 1.1, "input\n$x$", color="#f2f2f2")
    _box(ax, 2.4, 2.4, 2.4, 1.1, "$W_0$  (frozen)\n$d \\times d$",
         color="#dddddd", fontsize=9)
    _box(ax, 2.4, 0.5, 1.1, 1.1, "$A$\n$d\\times r$", color=COLORS["transformer"], fontsize=8.5)
    _box(ax, 3.7, 0.5, 1.1, 1.1, "$B$\n$r\\times d$", color=COLORS["transformer"], fontsize=8.5)
    _arrow(ax, (1.7, 2.25), (2.4, 2.95))
    _arrow(ax, (1.7, 2.25), (2.4, 1.05))
    _arrow(ax, (3.5, 1.05), (3.7, 1.05))
    _arrow(ax, (4.8, 2.95), (5.9, 2.2))
    _arrow(ax, (4.8, 1.05), (5.9, 1.9))
    ax.add_patch(Circle((6.2, 2.05), 0.33, facecolor="#ffffff", edgecolor="#333"))
    ax.text(6.2, 2.05, "+", ha="center", va="center", fontsize=14)
    _arrow(ax, (6.55, 2.05), (7.4, 2.05))
    _box(ax, 7.4, 1.5, 1.7, 1.1, "output\n$h$", color=COLORS["tree"])
    ax.text(
        0.4, 0.05,
        "$h = W_0x + BAx$ with $r \\ll d$.  Only $A$ and $B$ are trained, typically "
        "well under 1% of the parameters,\nand at inference $BA$ can be folded into $W_0$ "
        "so there is no extra latency.",
        fontsize=9,
    )
    ax.set_ylim(-0.2, 4.2)
    ax.set_title("LoRA: parameter-efficient fine-tuning", fontsize=11, fontweight="bold")
    return fig


def rag_architecture() -> plt.Figure:
    """RAG is plumbing around a frozen model — it does not train anything."""
    fig, ax = _canvas(11.5, 3.8)
    _box(ax, 0.3, 1.6, 1.7, 1.0, "question", color="#f2f2f2")
    _arrow(ax, (2.0, 2.1), (2.8, 2.1))
    _box(ax, 2.8, 1.6, 1.8, 1.0, "embed +\nretrieve", color=COLORS["mlp"], fontsize=9)
    _arrow(ax, (3.7, 1.55), (3.7, 0.95))
    _box(ax, 2.6, 0.1, 2.2, 0.8, "document store\n(your standards, logs)",
         color=COLORS["accent"], fontsize=8.5)
    _arrow(ax, (4.6, 2.1), (5.4, 2.1))
    _box(ax, 5.4, 1.5, 2.1, 1.2, "prompt =\nquestion +\nretrieved text",
         color="#f2f2f2", fontsize=8.5)
    _arrow(ax, (7.5, 2.1), (8.3, 2.1))
    _box(ax, 8.3, 1.5, 1.9, 1.2, "frozen LLM\n(weights\nunchanged)",
         color=COLORS["foundation"], fontsize=8.5)
    _arrow(ax, (10.2, 2.1), (11.0, 2.1))
    ax.text(11.15, 2.1, "answer", fontsize=9, va="center")
    ax.text(
        0.3, 3.2,
        "Misconception: 'RAG trains the model.' It does not. Not one weight changes — "
        "the retrieved text\nenters through the context window, exactly like anything else "
        "you type into the prompt.",
        fontsize=9.5, color=COLORS["transformer"],
    )
    ax.set_xlim(0, 12.2)
    ax.set_title("Retrieval-augmented generation is a system architecture", fontsize=11,
                 fontweight="bold")
    return fig


def paradigm_shift() -> plt.Figure:
    """One-task-one-model versus broad pretraining plus adaptation."""
    fig, axes = plt.subplots(1, 2, figsize=(12, 4.4))
    for ax in axes:
        ax.set_xlim(0, 10)
        ax.set_ylim(0, 10)
        ax.axis("off")
        ax.grid(False)

    ax = axes[0]
    for i, (task, dataset) in enumerate(
        [("load\nforecast", "PV plant A"), ("voltage\nestimate", "feeder B"),
         ("congestion\npredict", "region C")]
    ):
        x = 0.4 + i * 3.2
        _box(ax, x, 7.4, 2.7, 1.5, f"dataset:\n{dataset}", color="#f2f2f2", fontsize=8.5)
        _arrow(ax, (x + 1.35, 7.3), (x + 1.35, 6.0))
        _box(ax, x, 4.3, 2.7, 1.6, "its own\nmodel", color=COLORS["linear"], fontsize=8.5)
        _arrow(ax, (x + 1.35, 4.2), (x + 1.35, 2.9))
        _box(ax, x, 1.3, 2.7, 1.5, task, color=COLORS["tree"], fontsize=8.5)
    ax.text(5.0, 0.3, "N tasks -> N models -> N labelled datasets", ha="center", fontsize=9.5,
            style="italic")
    ax.set_title("One dataset, one task, one model", fontsize=10.5, fontweight="bold")

    ax = axes[1]
    _box(ax, 1.2, 8.0, 7.6, 1.5, "BROAD PRETRAINING\nmany grids / plants / years, unlabelled",
         color=COLORS["foundation"], fontsize=9)
    _arrow(ax, (5.0, 7.9), (5.0, 6.9), lw=2.0)
    _box(ax, 2.6, 5.2, 4.8, 1.6, "REUSABLE REPRESENTATION", color=COLORS["accent"], fontsize=9.5,
         weight="bold")
    for i, (task, how) in enumerate(
        [("task A", "zero-shot"), ("task B", "few-shot"), ("task C", "fine-tune")]
    ):
        x = 0.4 + i * 3.2
        _arrow(ax, (5.0, 5.1), (x + 1.35, 3.6), rad=0.1)
        _box(ax, x, 2.1, 2.7, 1.4, f"{task}\n({how})", color=COLORS["tree"], fontsize=8.5)
    ax.text(5.0, 0.9, "N tasks -> 1 backbone + N small adaptations", ha="center", fontsize=9.5,
            style="italic")
    ax.set_title("Broad pretraining, then adaptation", fontsize=10.5, fontweight="bold")
    fig.suptitle("The paradigm shift this course is about", fontsize=11.5, fontweight="bold")
    fig.tight_layout()
    return fig


def foundation_model_modalities() -> plt.Figure:
    """Foundation models across domains — language is one column of many."""
    fig, ax = _canvas(12, 4.6, xlim=(0, 12), ylim=(0, 4.6))
    domains = [
        ("Language\n/ code", "GPT, Llama,\nQwen, Mistral", COLORS["foundation"]),
        ("Vision", "DINOv2, CLIP,\nSAM 2", COLORS["mlp"]),
        ("Biology", "ESM-2,\nAlphaFold", COLORS["tree"]),
        ("Weather", "GraphCast,\nAurora, GenCast", COLORS["rnn"]),
        ("Time series", "Chronos-2,\nTimesFM, Moirai", COLORS["transformer"]),
        ("Tabular", "TabPFN", COLORS["linear"]),
        ("Robotics", "RT-2, OpenVLA,\nOcto, pi-0", COLORS["accent"]),
        ("Power grids", "GridFM, PowerPM,\nGridSFM, WindFM", "#bbbbbb"),
    ]
    width = 1.35
    gap = (12 - 0.5 - len(domains) * width) / (len(domains) - 1)
    for i, (name, models, colour) in enumerate(domains):
        x = 0.25 + i * (width + gap)
        _box(ax, x, 2.5, width, 1.1, name, color=colour, fontsize=8.5, weight="bold")
        ax.text(x + width / 2, 1.85, models, ha="center", va="top", fontsize=7.4)
    ax.text(
        6.0, 4.15,
        "Same recipe: pretrain a big model on a broad distribution with a self-supervised "
        "objective, then adapt.",
        ha="center", fontsize=9.5,
    )
    ax.text(
        6.0, 0.45,
        "Only the first column is a 'large language model'. "
        "Foundation model is the broader category.",
        ha="center", fontsize=9.5, style="italic", color=COLORS["transformer"],
    )
    ax.set_title("Foundation models are not only LLMs", fontsize=11, fontweight="bold")
    return fig


def gridfm_architecture() -> plt.Figure:
    """A candidate architecture for a grid foundation model."""
    fig, ax = _canvas(12.4, 5.6, xlim=(0, 12.4), ylim=(-0.3, 5.6))
    modalities = [
        ("time series\nP, Q, V, I, f\nPMU, SCADA, meters", COLORS["rnn"]),
        ("topology\nbuses, branches,\nswitches, trafos", COLORS["mlp"]),
        ("static metadata\nvoltage level,\nequipment type", COLORS["linear"]),
        ("weather\n& market\nsignals", COLORS["tree"]),
        ("text\nlogs, reports,\nstandards", COLORS["accent"]),
    ]
    width, gap = 1.72, 0.3
    for i, (label, colour) in enumerate(modalities):
        x = 0.25 + i * (width + gap)
        _box(ax, x, 4.2, width, 1.15, label, color=colour, fontsize=7.6)
        _arrow(ax, (x + width / 2, 4.15), (5.1, 3.5), rad=0.05)
    _box(ax, 1.1, 2.5, 8.0, 0.95, "tokenizer / embedding: what is a 'token' of a grid?",
         color="#f2f2f2", fontsize=9)
    _arrow(ax, (5.1, 2.45), (5.1, 2.1))
    _box(ax, 1.1, 1.0, 8.0, 1.05,
         "graph transformer encoder\n(topology-aware, permutation-equivariant)",
         color=COLORS["foundation"], fontsize=9, weight="bold")
    _box(ax, 9.5, 1.6, 2.7, 1.8,
         "pretraining objective\n\nmasked node / edge\nreconstruction\n"
         "+ physics loss\n(AC power balance)",
         color="#f7f7f7", fontsize=7.8)
    _arrow(ax, (9.45, 2.1), (9.15, 2.1), style="<|-")
    ax.text(0.25, 0.35,
            "downstream: power flow, state estimation, contingency screening, "
            "voltage control, anomaly detection", fontsize=8.5, style="italic")
    ax.set_title("A proposed Grid Foundation Model architecture", fontsize=11, fontweight="bold")
    return fig


def multi_grid_transfer() -> plt.Figure:
    """Pretrain across grids, transfer to an unseen one."""
    fig, ax = _canvas(11.5, 4.4, xlim=(0, 11.5), ylim=(0, 4.4))
    rng = np.random.default_rng(3)
    for i, (name, n_nodes) in enumerate([("grid A\n9 bus", 9), ("grid B\n30 bus", 14),
                                         ("grid C\n39 bus", 11)]):
        cx = 1.2 + i * 2.0
        points = rng.normal(0, 0.32, size=(n_nodes, 2)) + [cx, 3.4]
        for a in range(n_nodes - 1):
            ax.plot(points[a : a + 2, 0], points[a : a + 2, 1], color="#999", lw=0.7, zorder=1)
        ax.scatter(points[:, 0], points[:, 1], s=16, color=COLORS["mlp"], zorder=2)
        ax.text(cx, 2.45, name, ha="center", fontsize=8.5)
        _arrow(ax, (cx, 2.3), (6.4, 1.75), rad=0.08)
    _box(ax, 6.4, 1.2, 2.4, 1.1, "ONE encoder\n(shared weights)", color=COLORS["foundation"],
         fontsize=9, weight="bold")
    _arrow(ax, (8.9, 1.75), (9.6, 1.75), lw=2.0)
    points = rng.normal(0, 0.38, size=(18, 2)) + [10.4, 3.2]
    for a in range(17):
        ax.plot(points[a : a + 2, 0], points[a : a + 2, 1], color="#999", lw=0.7, zorder=1)
    ax.scatter(points[:, 0], points[:, 1], s=16, color=COLORS["transformer"], zorder=2)
    ax.text(10.4, 2.3, "unseen grid\n(held out)", ha="center", fontsize=8.5,
            color=COLORS["transformer"])
    ax.text(
        0.3, 0.4,
        "The parameters live in the message and update functions, which are shared by every bus "
        "and every branch.\nNothing in the model has a fixed bus count — that is what makes "
        "transfer to a different topology possible at all.",
        fontsize=9,
    )
    ax.set_title("Multi-grid pretraining and transfer", fontsize=11, fontweight="bold")
    return fig


def ai_timeline() -> plt.Figure:
    """The milestones the course walks through.

    Two panels, not one, because a single linear axis makes everything after
    2015 illegible — and that illegibility is itself the point: the field did
    in the last decade what it had previously done in five.

    Dates are the year of first public release (arXiv preprint where one
    exists), not journal publication. Several are genuinely contested — the
    perceptron, backpropagation and attention all have earlier partial
    antecedents — so read this as a teaching aid, not as priority claims.
    """
    early = [
        (1957, "Perceptron\n(Rosenblatt)"),
        (1986, "Backprop popularised\n(Rumelhart et al.)"),
        (1997, "LSTM\n(Hochreiter & Schmidhuber)"),
        (1998, "LeNet-5\n(LeCun et al.)"),
        (2006, "Deep learning\nresurgence"),
    ]
    modern = [
        (2012, "AlexNet"),
        (2013, "Word2Vec"),
        (2014, "Seq2seq; attention\n(Bahdanau)"),
        (2017, "Transformer"),
        (2018, "BERT / GPT"),
        (2020, "GPT-3; scaling laws"),
        (2021, "'Foundation model'\ncoined; CLIP"),
        (2022, "InstructGPT;\nchat models"),
        (2023, "Open-model wave;\nSAM; DINOv2"),
        (2024, "Time-series &\nscience FMs"),
        (2025, "Domain-specific FMs\n(WindFM, ...)"),
        (2026, "Grid foundation\nmodels"),
    ]

    fig, axes = plt.subplots(2, 1, figsize=(12.5, 6.2))
    panels = [
        (axes[0], early, 1950, 2011, "1950 - 2010:  the long build-up", COLORS["rnn"]),
        (axes[1], modern, 2011, 2027, "2011 - 2026:  the acceleration", COLORS["foundation"]),
    ]
    for ax, events, x0, x1, title, colour in panels:
        ax.axhline(0, color="#333333", lw=1.5)
        for i, (year, label) in enumerate(events):
            side = 1 if i % 2 == 0 else -1
            ax.plot([year, year], [0, 0.30 * side], color=colour, lw=1.2)
            ax.plot(year, 0, "o", ms=5, color=colour)
            ax.text(
                year, 0.38 * side, f"{year}\n{label}", ha="center",
                va="bottom" if side > 0 else "top", fontsize=8.0,
            )
        ax.set_xlim(x0, x1)
        ax.set_ylim(-1.5, 1.5)
        ax.set_yticks([])
        ax.spines[["left", "right", "top"]].set_visible(False)
        ax.grid(axis="x", alpha=0.2)
        ax.set_title(title, fontsize=10, fontweight="bold", loc="left")
    fig.suptitle(
        "Milestones on the way from machine learning to foundation models",
        fontsize=11.5, fontweight="bold",
    )
    fig.tight_layout()
    return fig
